### ISSUE TITLE
Fatal error: Property 'line' of object #<Object> is not a function

### ISSUE THREAD

**Issue by scriby** [palantir/grunt-tslint#23]
I updated to grunt-tslint 2.0.0 and now I get this error when linting my codebase. Let me know if you need more info and I can dig into it some more. (FYI, I get the same error under 2.3.0-beta)

```
TypeError: Property 'line' of object #<Object> is not a function
    at Formatter.format (.../tslintFormatter.js:20:41)
    at Linter.lint (.../node_modules/tslint/lib/tslint.js:42523:36)
    at .../node_modules/grunt-tslint/tasks/tslint.js:39:29
    at .../node_modules/grunt/node_modules/async/lib/async.js:201:13
    at iterate (.../node_modules/grunt/node_modules/async/lib/async.js:108:13)
    at .../node_modules/grunt/node_modules/async/lib/async.js:119:25
    at .../node_modules/grunt/node_modules/async/lib/async.js:203:17
    at null._onTimeout (.../node_modules/grunt-tslint/tasks/tslint.js:67:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by adidahiya** [comment]
Is this still an issue @scriby?

**Comment by blaiz** [comment]
I just updated to grunt-tslint 2.5.0 and I'm getting the same error.

PS: I'm working on the same project as scriby so it might be related to the project.
